modify workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,29 +43,29 @@ jobs:
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
 
-      - name: Azure Login
-        uses: azure/login@v1
-        with:
-          creds: ${{ secrets.AZURE_SECRET }}
+      # - name: Azure Login
+      #   uses: azure/login@v1
+      #   with:
+      #     creds: ${{ secrets.AZURE_SECRET }}
 
-      - name: Authenticate with AKS
-        run: |
-          az aks install-cli
-          az aks get-credentials -g ${{ vars.AZURE_GROUP }} --n ${{ vars.AZURE_CLUSTER }}
+      # - name: Authenticate with AKS
+      #   run: |
+      #     az aks install-cli
+      #     az aks get-credentials -g ${{ vars.AZURE_GROUP }} --n ${{ vars.AZURE_CLUSTER }}
 
-      - name: Allow GitHub Runner in AKS Authorized API Ranges
-        run: |
-          agentIP=$(curl -s https://api.ipify.org/)
-          az aks update -g ${{ vars.AZURE_GROUP }} -n ${{ vars.AZURE_CLUSTER }} --api-server-authorized-ip-ranges $agentIP/32,${{ secrets.IPADDR_WHITELIST }}
-          sleep 100
+      # - name: Allow GitHub Runner in AKS Authorized API Ranges
+      #   run: |
+      #     agentIP=$(curl -s https://api.ipify.org/)
+      #     az aks update -g ${{ vars.AZURE_GROUP }} -n ${{ vars.AZURE_CLUSTER }} --api-server-authorized-ip-ranges $agentIP/32,${{ secrets.IPADDR_WHITELIST }}
+      #     sleep 100
     
-      - name: Apply Manifests
-        run: |
-          kubectl apply -f ./manifests/bot.yaml
-          kubectl rollout restart deployment melpominee-bot --namespace=melpominee
+      # - name: Apply Manifests
+      #   run: |
+      #     kubectl apply -f ./manifests/bot.yaml
+      #     kubectl rollout restart deployment melpominee-bot --namespace=melpominee
     
-      - name: Restore AKS Authorized API Ranges
-        run: |
-          agentIP=$(curl -s https://api.ipify.org/)
-          az aks update -g ${{ vars.AZURE_GROUP }} -n ${{ vars.AZURE_CLUSTER }} --api-server-authorized-ip-ranges ${{ secrets.IPADDR_WHITELIST }}
-        if: success() || failure()
+      # - name: Restore AKS Authorized API Ranges
+      #   run: |
+      #     agentIP=$(curl -s https://api.ipify.org/)
+      #     az aks update -g ${{ vars.AZURE_GROUP }} -n ${{ vars.AZURE_CLUSTER }} --api-server-authorized-ip-ranges ${{ secrets.IPADDR_WHITELIST }}
+      #   if: success() || failure()
